<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="appsettings.Development.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.Development.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="8.14.0" />
    <PackageReference Include="Z.Blazor.Diagrams" Version="3.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataSettMetamodel\DataSettMetamodel.csproj" />
    <ProjectReference Include="..\DataSettViewModel\DataSettViewModel.csproj" />
  </ItemGroup>

</Project>
